pub mod about_section;
pub mod career_section;
pub mod certifications_section;
mod data;
pub mod education_section;
pub mod footer_section;
pub mod go_to_top;
pub mod header_section;
pub mod languages_section;
pub mod nav_section;
pub mod projects_section;
pub mod skills_section;

pub use about_section::AboutSection;
pub use career_section::CareerSection;
pub use certifications_section::CertificationsSection;
pub use education_section::EducationSection;
pub use footer_section::FooterSection;
pub use go_to_top::GoToTop;
pub use header_section::HeaderSection;
pub use languages_section::LanguagesSection;
pub use nav_section::NavSection;
pub use projects_section::ProjectsSection;
pub use skills_section::SkillsSection;
