pub mod about_section;
pub mod experience_section;
pub mod certifications_section;
mod data;
pub mod education_section;
pub mod footer_section;
pub mod scroll_to_top;
pub mod header_section;
pub mod languages_section;
pub mod nav_section;
pub mod projects_section;
pub mod skills_section;
pub mod contact_section;

pub use header_section::HeaderSection;
pub use contact_section::ContactSection;
pub use about_section::AboutSection;
pub use experience_section::ExperienceSection;
pub use certifications_section::CertificationsSection;
pub use education_section::EducationSection;
pub use footer_section::FooterSection;
pub use scroll_to_top::ScrollToTop;
pub use languages_section::LanguagesSection;
pub use nav_section::NavSection;
pub use projects_section::ProjectsSection;
pub use skills_section::SkillsSection;
